"""
Phase 0A -- oracle label collection.

Walk trajectories generated by pi_ref, snapshot states s_t, and at each snapshot
estimate the policy-relative advantage A^{pi_ref}(i | s_t) of committing
(i, x_hat_i) by CRN-coupled paired rollouts. Nothing here trains; the backbone
is frozen and no gradient is taken through a rollout.

Every stored label is POLICY-RELATIVE: it is A^{pi_ref}, never A*.

FROZEN before any probe was fitted (brief 0A.1), chosen from a pilot that
measured label signal-to-noise, NOT from probe results:
  pi_ref    ancestral uniform-random-order unmasking, 1 commit/step,
            top_k=50, temperature 1.0                      (see policy.py)
  G         Rao-Blackwellised Path-LL. The realised-token estimator was
            measured to have SNR 0.1-0.6 at this scale -- its rollout noise
            EXCEEDS the between-candidate signal, so it cannot support any
            conclusion. The Rao-Blackwellised estimator reaches SNR 2-4.
  horizon   H = 16 pi_ref commits scored after the decision point. Longer
            horizons dilute a single token's effect across more future
            randomness (measured SNR falls to ~1 at H=None).
  K         24 CRN-coupled paired rollouts per branch. K=8 left the
            downstream-only label A_future at SNR 0.74 (ancestral) / 0.59
            (confidence) -- below 1, so its null was uninformative rather than
            evidence of absence. Noise falls as 1/K; K=24 lifts A_future to a
            projected SNR of ~2.2 / ~1.8 and its R^2 ceiling from 0.43 to ~0.69.
  labels    A_full   = advantage of the per-token Path-LL INCLUDING the forced
                       action's own log-probability (literal POKE Path-LL)
            A_future = the action's downstream effect only. Harder, because the
                       action's own log-probability IS a cheap control feature.
            Both are reported; both were pre-registered.
"""
import os
from dataclasses import dataclass, field, asdict

import numpy as np
import torch

from crn import uniforms
from features import PROJ_DIM, ProjCache, TOPK_FEATS
from mdlm_local import MASK_TOKEN_ID
from policy import (PiRefConfig, forward_raw, topk_logprobs, rollout,
                    make_initial_state)


@dataclass
class CollectConfig:
    seq_len: int = 256
    prefix_len: int = 64
    temperature: float = 1.0
    top_k: int = 50
    order: str = "ancestral"
    order_temp: float = 1.0
    # Late-trajectory states are excluded: with a FIXED horizon H the label is
    # not comparable across bins unless H stays a small fraction of what
    # remains. At 0.85 progress only 29 positions remained, so H=16 covered 55%
    # of the rest, against 9% at 0.10. Capping at 0.60 keeps H/remaining in
    # [0.09, 0.21] across every bin.
    record_fracs: tuple = (0.10, 0.20, 0.30, 0.40, 0.50, 0.60)
    n_cand: int = 6            # candidate positions per state
    n_cand_conf: int = 3       # of which, drawn from the high-confidence stratum
    K: int = 24                # CRN-coupled rollouts per branch
    horizon: int = 16          # pi_ref commits scored after the decision point
    traj_batch: int = 6        # prompts decoded together
    rollout_batch: int = 48    # branch rollouts per forward
    store_layers: tuple = tuple(range(13))
    seed_base: int = 1_000_003

    def pi(self):
        return PiRefConfig(seq_len=self.seq_len, prefix_len=self.prefix_len,
                           temperature=self.temperature, top_k=self.top_k,
                           order=self.order, order_temp=self.order_temp)


# --------------------------------------------------------------- snapshots ---
@torch.no_grad()
def project_logprobs(logits, lse, device, chunk=32):
    """Fixed JL projection of the FULL log-probability vector (C3 control).

    log p = logit - lse, so  (log p) @ P = logits @ P - lse * colsum(P),
    which avoids ever materialising the full log-prob tensor.
    """
    V = logits.shape[-1]
    P = ProjCache.get(V, device)
    colsum = P.sum(0)
    B, L, _ = logits.shape
    out = torch.empty(B, L, P.shape[1], dtype=torch.float32, device=device)
    for a in range(0, L, chunk):
        out[:, a:a + chunk] = (logits[:, a:a + chunk].float() @ P
                               - lse[:, a:a + chunk, None] * colsum)
    return out


@torch.no_grad()
def snapshot(model, ids, mask, step, hist, cfg, pcfg):
    """Everything measurable at state s_t, before any rollout is run."""
    logits, hs = forward_raw(model, ids, output_hidden_states=True)
    lp_top, idx, lse, lg_top = topk_logprobs(logits, cfg.top_k, 32)
    proj = project_logprobs(logits, lse, ids.device)

    argmax = idx[..., 0]
    p1 = lp_top[..., 0].exp()
    if hist["prev_logits"] is None:
        tkl = torch.zeros_like(p1)
        dp1 = torch.zeros_like(p1)
    else:
        # KL(p_t || p_{t-1}) restricted to the top-k support of p_t
        prev_lp = (hist["prev_logits"].gather(-1, idx).float()
                   - hist["prev_lse"][..., None])
        p = lp_top.exp()
        tkl = (p * (lp_top - prev_lp)).sum(-1)
        dp1 = p1 - hist["prev_p1"]

    flip_count, persistence = history_counts_at_state(hist, argmax, mask)
    snap = {
        "ids": ids.clone(), "mask": mask.clone(), "step": step,
        "lp_top": lp_top, "lg_top": lg_top, "idx": idx, "proj": proj,
        "argmax": argmax,
        "temporal_kl": tkl, "dp1": dp1,
        "flip_count": flip_count.clone(),
        "persistence": persistence.clone(),
        "hidden": [hs[l] for l in cfg.store_layers],
        "prefix_len": cfg.prefix_len,
    }
    return snap, (logits, lse, p1, argmax)


def history_counts_at_state(hist, argmax, mask):
    """Return stability counts including the transition into the current state.

    Snapshot features and temporal KL/dp1 all describe the current state versus
    the previous state.  The old online collector snapshotted the counters before
    adding this transition, shifting flip/persistence by one state.  Keep this
    pure helper shared by snapshot and update so their definitions cannot drift.
    """
    flip_count = hist["flip_count"]
    persistence = hist["persistence"]
    if hist["prev_argmax"] is not None:
        flip = (argmax != hist["prev_argmax"]).float()
        flip_count = flip_count + flip * mask.float()
        persistence = torch.where(
            flip.bool(), torch.zeros_like(persistence), persistence + 1.0)
    return flip_count, persistence


def update_hist(hist, logits, lse, p1, argmax, mask):
    """Advance the trajectory history by ONE denoising step.

    Must be called at EVERY step, not only at recorded ones: flip_count and
    persistence are per-step realised-trajectory statistics (the TraceLock-style
    stability controls). Accumulating them only at the recorded checkpoints
    coarsens them and weakens the control baseline, which would bias the study
    in favour of its own hypothesis.
    """
    hist["flip_count"], hist["persistence"] = history_counts_at_state(
        hist, argmax, mask)
    hist["prev_logits"] = logits
    hist["prev_lse"] = lse
    hist["prev_p1"] = p1
    hist["prev_argmax"] = argmax


def new_hist(B, L, device):
    return {"prev_logits": None, "prev_lse": None, "prev_p1": None,
            "prev_argmax": None,
            "flip_count": torch.zeros(B, L, device=device),
            "persistence": torch.zeros(B, L, device=device)}


# ------------------------------------------------------------- candidates ---
def pick_candidates(snap, cfg, gen):
    """Stratified candidate positions per row.

    Stratum 0 ("natural"): uniformly sampled masked positions -- this is the
      naturally-sampled population and the one the held-out test metrics are
      reported on separately.
    Stratum 1 ("informative"): high-confidence x high-instability positions,
      oversampled per the brief to enrich the decision-relevant region.
    """
    mask = snap["mask"]
    B, L = mask.shape
    dev = mask.device
    n_nat = cfg.n_cand - cfg.n_cand_conf

    cb, ci, cs = [], [], []
    conf = snap["lp_top"][..., 0]
    instab = snap["temporal_kl"] + 0.5 * snap["flip_count"]
    info_score = torch.where(mask, conf + instab, torch.full_like(conf, -1e30))
    rnd = torch.where(mask, torch.rand(mask.shape, generator=gen, device=dev),
                      torch.full_like(conf, -1e30))
    for b in range(B):
        nm = int(mask[b].sum().item())
        if nm == 0:
            continue
        k_nat = min(n_nat, nm)
        nat = rnd[b].topk(k_nat).indices
        k_inf = min(cfg.n_cand_conf, nm - k_nat)
        if k_inf > 0:
            sc = info_score[b].clone()
            sc[nat] = -1e30
            inf = sc.topk(k_inf).indices
        else:
            inf = torch.empty(0, dtype=torch.long, device=dev)
        for p in nat.tolist():
            cb.append(b); ci.append(p); cs.append(0)
        for p in inf.tolist():
            cb.append(b); ci.append(p); cs.append(1)
    return (torch.tensor(cb, device=dev), torch.tensor(ci, device=dev),
            np.array(cs, dtype=np.int8))


# ---------------------------------------------------------------- rollouts ---
@torch.no_grad()
def branch_rollouts(model, snap, cand_b, cand_i, cfg, pcfg, seed_offset):
    """Paired CRN rollouts -> Q, V, A for every candidate.

    Branch V for prompt b and seed k, and branch Q for (b, i, k), use the SAME
    rollout seed, hence identical unmasking permutation and token Gumbels.
    """
    ids, mask = snap["ids"], snap["mask"]
    B, L = ids.shape
    dev = ids.device
    K = cfg.K
    N = cand_b.numel()

    # ---- V branches: (B, K) ------------------------------------------------
    v_ids = ids.repeat_interleave(K, 0)
    v_mask = mask.repeat_interleave(K, 0)
    v_seeds = (torch.arange(B, device=dev).repeat_interleave(K) * K
               + torch.arange(K, device=dev).repeat(B) + seed_offset)
    # V runs one commit LONGER than Q's continuation so that both branches
    # consume exactly H+1 positions of the mask pool.
    V = _chunked_rollout(model, v_ids, v_mask, v_seeds, pcfg, cfg,
                         horizon=(None if cfg.horizon is None
                                  else cfg.horizon + 1))

    # ---- Q branches: (N, K) ------------------------------------------------
    xhat = snap["argmax"][cand_b, cand_i]                       # (N,)
    logp_action = snap["lp_top"][cand_b, cand_i, 0]             # full-softmax
    q_ids = ids[cand_b].repeat_interleave(K, 0)
    q_mask = mask[cand_b].repeat_interleave(K, 0)
    rows = torch.arange(N * K, device=dev)
    pos = cand_i.repeat_interleave(K)
    q_ids[rows, pos] = xhat.repeat_interleave(K)
    q_mask[rows, pos] = False
    q_seeds = (cand_b.repeat_interleave(K) * K
               + torch.arange(K, device=dev).repeat(N) + seed_offset)
    Q = _chunked_rollout(model, q_ids, q_mask, q_seeds, pcfg, cfg,
                         horizon=cfg.horizon)

    out = {"logp_action": logp_action.float().cpu().numpy(),
           "incomplete": Q["incomplete"] + V["incomplete"]}

    def s_(x):
        return x.float().cpu().numpy()

    # Two Path-LL estimators (rb = Rao-Blackwellised, primary) and two label
    # variants (full = includes the forced action's own log-prob, as in the
    # literal POKE Path-LL; future = its downstream effect only).
    for est, key, fkey in (("rb", "path_ll_rb", "first_ll_rb"),
                           ("mc", "path_ll", "first_ll")):
        S_V = V[key].view(B, K)[cand_b]                          # (N, K), H+1 commits
        v_first = V[fkey].view(B, K)[cand_b]                     # V's own commit at t
        V_n = V["n_commit"].view(B, K)[cand_b]
        S_Q = Q[key].view(N, K)                                  # (N, K), H commits
        Q_n = Q["n_commit"].view(N, K)

        # both branches consumed Q_n + 1 == V_n positions
        n_full = (Q_n + 1).clamp(min=1).double()
        per_tok_Q_full = (S_Q + logp_action[:, None].double()) / n_full
        per_tok_V_full = S_V / V_n.clamp(min=1).double()
        A_full = per_tok_Q_full - per_tok_V_full

        # downstream-only: H commits after the decision on each side
        n_fut = Q_n.clamp(min=1).double()
        per_tok_Q_fut = S_Q / n_fut
        per_tok_V_fut = (S_V - v_first) / (V_n - 1).clamp(min=1).double()
        A_future = per_tok_Q_fut - per_tok_V_fut

        p = "" if est == "rb" else "mc_"
        out[f"{p}A_full_seeds"] = s_(A_full)
        out[f"{p}A_future_seeds"] = s_(A_future)
        out[f"{p}A_pertok"] = s_(A_full.mean(1))
        out[f"{p}A_future"] = s_(A_future.mean(1))
        out[f"{p}A_sem"] = s_(A_full.std(1) / np.sqrt(K))
        out[f"{p}A_future_sem"] = s_(A_future.std(1) / np.sqrt(K))
        out[f"{p}Q_pertok"] = s_(per_tok_Q_full.mean(1))
        out[f"{p}V_pertok"] = s_(per_tok_V_full.mean(1))
        out[f"{p}Q_sd"] = s_(per_tok_Q_full.std(1))
        out[f"{p}V_sd"] = s_(per_tok_V_full.std(1))
        # per-seed replicates for V too, so the state value gets a noise
        # ceiling of its own. Without these V's Delta_R2 cannot be
        # ceiling-corrected and cannot be reported as a finding in its own
        # right -- only as a foil for the advantage result.
        out[f"{p}V_pertok_seeds"] = s_(per_tok_V_full)
        out[f"{p}Q_pertok_seeds"] = s_(per_tok_Q_full)
        out[f"{p}V_n"] = s_(V_n[:, 0])
    out["n_commit"] = s_(Q["n_commit"].view(N, K)[:, 0] + 1)
    return out


def _chunked_rollout(model, ids, mask, seeds, pcfg, cfg, horizon=None):
    """Run rollouts in micro-batches, shrinking on OOM.

    The stride MUST follow the (possibly shrunken) micro-batch size. An earlier
    version wrote `for a in range(0, N, mb)` and then halved `mb` inside the
    loop on OOM, so the stride kept the ORIGINAL size while only half of each
    block was processed -- silently dropping rows. It surfaced only because the
    downstream `.view(B, K)` happened to catch the wrong element count.
    """
    keys = ["path_ll", "path_ll_rb", "first_ll", "first_ll_rb", "n_commit"]
    outs = {k: [] for k in keys}
    outs["incomplete"] = 0
    n = ids.shape[0]
    a = 0
    while a < n:
        mb = max(int(cfg.rollout_batch), 1)
        try:
            r = rollout(model, ids[a:a + mb], mask[a:a + mb],
                        seeds[a:a + mb], pcfg, horizon=horizon)
        except torch.cuda.OutOfMemoryError:
            torch.cuda.empty_cache()
            if mb == 1:
                raise
            cfg.rollout_batch = max(mb // 2, 1)
            continue
        for k in keys:
            outs[k].append(r[k])
        outs["incomplete"] += r["incomplete"]
        a += mb                      # advance by what was ACTUALLY processed
    res = {k: torch.cat(outs[k]) for k in keys}
    assert res["n_commit"].shape[0] == n, (
        f"chunked rollout returned {res['n_commit'].shape[0]} of {n} rows")
    res["incomplete"] = outs["incomplete"]
    return res
